name: .NET

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Configure NuGet
      run: dotnet nuget add source --username visionflexaustralia --password ${{ secrets.PACKAGE_KEY }} --store-password-in-clear-text --name visionflex-nuget "https://nuget.pkg.github.com/visionflexaustralia/index.json"
    - name: Restore dependencies
      run: dotnet restore ./UsbPcapLib.sln
    - name: Build
      run: dotnet build --no-restore ./UsbPcapLib.sln
    - name: Test
      run: dotnet test -c Release --verbosity normal --logger:junit ./UsbPcapLib.sln
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: /**/TestResults/TestResults.xml
        comment_mode: "update last"
