name: .NET Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./UsbPcapDotNet.sln
    - name: Build
      run: dotnet build --no-restore ./UsbPcapDotNet.sln
    - name: Test
      run: dotnet test -c Release --verbosity normal --logger:junit ./UsbPcapDotNet.sln
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: /**/TestResults/TestResults.xml
        comment_mode: "update last"
