name: Upload Nuget Packages

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish Nuget Packages
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ github.token }}

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - uses: microsoft/setup-msbuild@v1.0.2

    - name: Create NuGet Package
      run: dotnet pack -c Release

    - name: Glob Match
      uses: tj-actions/glob@v4
      id: glob
      with:
       files: |
        '**.nupkg'

    - name: Upload Package
      run: |
       ls bin
       ls bin/Release
       dotnet nuget push "bin\Release\*.nupkg" --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source "visionflex-nuget"

    - name: Upload Artifact
      if: failure()
      uses: actions/upload-artifact@v2.3.1
      with:
        path: '**.nupkg'
